name: NexEngine
main: su.nexmedia.engine.NexEngine
version: '${project.version} build-${buildNumber}'
description: Plugin Engine
author: NightExpress
softdepend: [ Vault ]
loadbefore: [ WorldGuard, MythicMobs, Citizens ]
api-version: 1.17
load: STARTUP
libraries:
  - com.zaxxer:HikariCP:5.0.1